[package]
name = "stdin"
version = "0.1.0"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
edition = "2018"

[dependencies]
tokio-fs = "0.1.5"
tokio-io = "0.1.11"
tokio-threadpool = "0.1.11"
futures = "0.1.25"
