[package]
name = "stdin"
version = "0.1.0"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
tokio-stdin = "0.1.1"
tokio-timer = "0.1"
image = "0.21.0"